import Head from "next/head"
import { BsFillMoonStarsFill } from "react-icons/bs"
import { AiFillTwitterCircle, AiFillLinkedin, AiFillGithub, AiFillInstagram } from "react-icons/ai"
import Image from "next/image"
import LineGradient from "../components/LineGradient"
import CSS from "../public/css.png"
import JavaScript from "../public/javascript.png"
import Reacts from "../public/react.png"
import Node from "../public/node.png"
import FireBase from "../public/firebase.png"
import GitHub from "../public/github.png"
import Tailwind from "../public/tailwind.png"
import Mongo from "../public/mongo.png"
import Education from "../components/Education.jsx"
import ishan from "../public/Ishan.jpg"
import Work from "../components/Work.jsx"
import web1 from "../public/web1.png"
import web2 from "../public/web2.png"
import web3 from "../public/web3.png"
import Capture from "../public/Capture.PNG"
import Capture2 from "../public/Capture2.PNG"
import Capture3 from "../public/Capture3.PNG"
import React from "react"
import { useState } from "react"
export default function Home() {
  const [darkmode, setdarkmode] = useState(false)

  return (
    <>
      <div className={darkmode ? "dark" : ""}>
        <Head>
          <title>Ishan Patni</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
          <section className=" min-h-screen">
            <nav className="py-10 mb-12 flex justify-between">
              <h1 className="text-xl font-burtons rounded-sm dark:text-white">Ishan Patni</h1>
              <ul className="flex items-center">
                <li>
                  <BsFillMoonStarsFill onClick={() => setdarkmode(!darkmode)} className="cursor-pointer text-2xl" />
                </li>
                <li>
                  <a href="https://drive.google.com/file/d/1jLGJZTZNsK2CVPAWXKgmhayixsBU766h/view?usp=share_link">
                    <h3 className="bg-gradient-to-r from-cyan-400 to-teal-200 bg-cyan-500 text-white px-4 py-2 rounded-md ml-8">Resume</h3>
                  </a>
                </li>
              </ul>
            </nav>
            <div className="text-center p-10">
              <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl ">Ishan Patni</h2>
              <h3 className="text-2xl py-2  font-medium md:text-3xl dark:text-white">Software Engineer</h3>
              <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-slate-200">
                Hi! I am a web developer and have worked in quite a few technologies. I am currently in my final semester of Engineering from Bengaluru in Computer Science.
              </p>
            </div>
            <div className="text-5xl flex justify-center gap-14 py-3 text-gray-600 dark:text-white">
              <a href="https://www.instagram.com/ishanpatni01/">
                <AiFillInstagram />
              </a>
              <a href="https://github.com/IshanPatni30/">
                <AiFillGithub />
              </a>
              <a href="">
                <AiFillLinkedin />
              </a>
            </div>
            <div className="relative mx-auto border-8 border-cyan-300 bg-gradient from-teal-500 to-teal-100 rounded-3xl overflow-hidden  w-96 h-500 mt-20">
              <Image src={ishan} />
            </div>
          </section>

          <section>
            <div className="py-10 m-10">
              <h3 className="text-3xl mt-10 mb-10 py-1 dark:text-white">How can I add value?</h3>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-slate-200">
                Honestly, I possess all the skills and experience that you’re looking for. I’m pretty confident that I am the best candidate for this job role. It’s not just my background in the past
                projects, but also my people skills, which will be applicable in this position. On the other hand, I am a self motivated person and I try to exceed my superior’s expectations with
                high-quality work. Being a fast learner, I quickly pick up business knowledge related to my project. Lastly, I would like to add that I work well both as an individual contributor and
                also as a team member.
              </p>
            </div>
          </section>
          <section>
            <div name="skills" className=" h-screen py-10 m-10 mb-8 ">
              {/* Container */}
              <div>
                <p className="text-4xl font-bold inline  border-b-4 border-cyan-400 dark:text-white ">Skills</p>
                <p className="py-4 dark:text-slate-200"> These are the technologies I've worked with</p>
              </div>
              <div className="max-w-[1000px] mx-auto flex flex-col justify-center w-full h-full">
                <div className="w-full grid grid-cols-2 sm:grid-cols-4 gap-4 text-center  ">
                  <div className="shadow-md shadow-[#040c16] hover:scale-110 duration-500 bg-gradient-to-b from-cyan-300 to-teal-500 ">
                    <Image className="w-20 mx-auto" src={JavaScript} alt="HTML icon" />
                    <p className="my-4">JAVASCRIPT</p>
                  </div>
                  <div className="shadow-md shadow-[#040c16] hover:scale-110 duration-500 bg-gradient-to-b from-cyan-300 to-teal-500">
                    <Image className="w-20 mx-auto" src={Reacts} alt="HTML icon" />
                    <p className="my-4">REACT</p>
                  </div>

                  <div className="shadow-md shadow-[#040c16] hover:scale-110 duration-500 bg-gradient-to-b from-cyan-300 to-teal-500">
                    <Image className="w-20 mx-auto" src={Node} alt="HTML icon" />
                    <p className="my-4">NODE JS</p>
                  </div>
                  <div className="shadow-md shadow-[#040c16] hover:scale-110 duration-500 bg-gradient-to-b from-cyan-300 to-teal-500">
                    <Image className="w-20 mx-auto" src={Mongo} alt="HTML icon" />
                    <p className="my-4">MONGO DB</p>
                  </div>
                  <div className="shadow-md shadow-[#040c16] hover:scale-110 duration-500 bg-gradient-to-b from-cyan-300 to-teal-500">
                    <Image className="w-20 mx-auto" src={Tailwind} alt="HTML icon" />
                    <p className="my-4">TAILWIND</p>
                  </div>
                  <div className="shadow-md shadow-[#040c16] hover:scale-110 duration-500 bg-gradient-to-b from-cyan-300 to-teal-500">
                    <Image className="w-20 mx-auto" src={FireBase} alt="HTML icon" />
                    <p className="my-4">FIREBASE</p>
                  </div>
                  <div className="shadow-md shadow-[#040c16] hover:scale-110 duration-500 bg-gradient-to-b from-cyan-300 to-teal-500">
                    <Image className="w-20 mx-auto" src={GitHub} alt="HTML icon" />
                    <p className="my-4">GITHUB</p>
                  </div>
                  <div className="shadow-md shadow-[#040c16] hover:scale-110 duration-500 bg-gradient-to-b from-cyan-300 to-teal-500">
                    <Image className="w-20 mx-auto" src={CSS} alt="HTML icon" />
                    <p className="my-4">CSS</p>
                  </div>
                </div>
              </div>
            </div>
          </section>

          <section>
            <Education />
          </section>
          <section>
            <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
              <div className="basis-1/3 flex-1">
                <Image src={Capture3} className="rounded-lg object-cover width={'100%'} height={100%}" />
              </div>
              <div className="basis-1/3 flex-1">
                <Image src={Capture2} className="rounded-lg object-cover width={'100%'} height={100%}" />
              </div>
              <div className="basis-1/3 flex-1">
                <a href="https://netflix-react-4da94.web.app/">
                  <Image src={Capture} className="rounded-lg object-cover width={'100%'} height={100%}" />
                </a>
              </div>
            </div>
          </section>
        </main>
      </div>
    </>
  )
}
